services:
  app_proxy:
    environment:
      APP_HOST: jadelamo-coleccion
      APP_PORT: 41100

  coleccion:
    image: ghcr.io/nerusete/jadelamo-coleccion:1.0.2
    container_name: jadelamo-coleccion
    restart: unless-stopped
    init: true
    environment:
      TZ: Europe/Madrid
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
