services:
  app_proxy:
    environment:
      APP_HOST: jadelamo-lando_lando_1
      APP_PORT: 7681

  lando:
    image: ghcr.io/nerusete/jadelamo-lando:1.0.2
    restart: unless-stopped
    init: true

    environment:
      TZ: Europe/Madrid
      LANDO_HOME: /root/.lando
      DOCKER_HOST: unix:///var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/umbrel/umbrel/data/storage/lando-projects:/home/umbrel/umbrel/data/storage/lando-projects:rw
      - ${APP_DATA_DIR}/data/lando:/root/.lando:rw

    working_dir: /home/umbrel/umbrel/data/storage/lando-projects
