server:
  port: 80
  sources:
    - name: Archivos
      path: /srv
      config:
        defaultEnabled: true

auth:
  methods:
    noauth: false
    password:
      enabled: true
      signup: false
