services:
  filebrowser-quantum:
    image: gtstef/filebrowser:1.5.0-stable
    container_name: jadelamo-filebrowser-quantum
    restart: unless-stopped

    ports:
      - "8085:80"

    environment:
      FILEBROWSER_CONFIG: /home/filebrowser/data/config.yaml
      TZ: Europe/Madrid

    volumes:
      - ./data:/home/filebrowser/data
      - ./config.yaml:/home/filebrowser/data/config.yaml:ro
      - ./files:/srv
