services:
  filebrowser:
    container_name: jadelamo-filebrowser-quantum
    image: gtstef/filebrowser:beta
    restart: unless-stopped

    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: admin
      TZ: Europe/Madrid

    volumes:
      - ./files:/srv
      - ./data:/home/filebrowser/data

    ports:
      - "10700:80"
