services:
  filebrowser-quantum:
    image: gtstef/filebrowser:1.5.0-stable
    container_name: jadelamo-filebrowser-quantum
    restart: unless-stopped

    ports:
      - "8085:80"

    environment:
      FILEBROWSER_CONFIG: /home/filebrowser/config.yaml
      TZ: Europe/Madrid

    volumes:
      - ${UMBREL_ROOT}/:/storage
      - ${UMBREL_ROOT}/external/2T:/external
      - ${UMBREL_ROOT}/external/1TB:/external1
      - ${APP_DATA_DIR}/data/database:/home/filebrowser/database
      - ${APP_DATA_DIR}/data/config/config.yaml:/home/filebrowser/config.yaml
