version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jadelamo-lamp_web_1
      APP_PORT: 80

  web:
    image: webdevops/php-apache:8.3
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      PHP_MEMORY_LIMIT: 512M
      PHP_UPLOAD_MAX_FILESIZE: 256M
      PHP_POST_MAX_SIZE: 256M
    volumes:
      - ${APP_DATA_DIR}/data/htdocs:/app
    depends_on:
      - db

  db:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: jadelamo
      MARIADB_DATABASE: lamp
      TZ: Europe/Madrid
    volumes:
      - ${APP_DATA_DIR}/data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 256M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 600
      TZ: Europe/Madrid
    ports:
      - "41063:80"
    depends_on:
      - db
