services:
  xampp:
    image: tomsik68/xampp:latest
    container_name: jadelamo-xampp
    restart: unless-stopped
    init: true

    ports:
      - "41062:80"

    volumes:
      - ${UMBREL_ROOT}/data/storage/htdocs:/opt/lampp/htdocs:rw
