services:
  nodecast-tv:
    image: ghcr.io/technomancer702/nodecast-tv:latest
    container_name: jadelamo-nodecast-tv
    restart: unless-stopped

    ports:
      - "3000:3000"

    volumes:
      - ./data:/app/data

    environment:
      NODE_ENV: production
      PORT: 3000
