services:
  sun-panel:
    image: hslr/sun-panel:1.8.1
    container_name: jadelamo-sun-panel
    restart: unless-stopped

    ports:
      - "3002:3002"

    volumes:
      - ./conf:/app/conf
      - ./uploads:/app/uploads
      - ./database:/app/database

    environment:
      TZ: Europe/Madrid
