services:
  sun-panel:
    image: hslr/sun-panel:2.0.2-beta260912
    container_name: jadelamo-sun-panel
    restart: unless-stopped

    ports:
      - "3002:3002"

    volumes:
      - ./conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      TZ: Europe/Madrid
