version: "3.7"

services:
  sun-panel:
    image: hslr/sun-panel:beta
    container_name: jadelamo-sun-panel
    restart: on-failure

    volumes:
      - ${APP_DATA_DIR}/data/conf:/app/conf
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
      - ${APP_DATA_DIR}/data/database:/app/database
      - /var/run/docker.sock:/var/run/docker.sock 

    ports:
      - "3002:3002"
